//PRODUCT/TICKER DATA TYPES
export const CONNECT_TO_SOCKET = 'CONNECT_TO_SOCKET'
export const HANDLE_FEED = 'HANDLE_FEED'
export const GET_TICKER_DATA = 'GET_TICKER_DATA'

//LOADING AND CONNECTION STATUS TYPES
export const SET_LOADING = 'SET_LOADING'
export const SET_CONNECTION_STATUS = 'SET_CONNECTION_STATUS'
