//PRODUCT/TICKER DATA TYPES
export const CONNECT_TO_SOCKET = 'CONNECT_TO_SOCKET'
export const HANDLE_TICKER_DATA = 'HANDLE_TICKER_DATA'
export const HANDLE_LEVEL2_SNAPSHOT = 'HANDLE_LEVEL2_SNAPSHOT'
export const HANDLE_LEVEL2_UPDATE = 'HANDLE_LEVEL2_UPDATE'
export const GET_HISTORICAL_DATA = 'GET_HISTORICAL_DATA'
export const GET_ORDER_BOOK = 'GET_ORDER_BOOK'

//NEWS TYPES
export const GET_NEWS = 'GET_NEWS'

//ERROR TYPES
export const SOCKET_ERROR = 'SOCKET_ERROR'
export const DATA_ERROR = 'DATA_ERROR'

//LOADING AND CONNECTION STATUS TYPES
export const SET_LOADING = 'SET_LOADING'
export const SET_CONNECTION_STATUS = 'SET_CONNECTION_STATUS'
export const SET_ORDER_BOOK_LOADING = 'SET_ORDER_BOOK_LOADING'
